SessionId:
  name: sessionId
  in: path
  required: true
  schema:
    type: string
    minLength: 1
PageId:
  name: pageId
  in: path
  required: true
  schema:
    type: integer
    format: int64
    minimum: 1
DispatchId:
  name: dispatchId
  in: path
  required: true
  schema:
    type: integer
    format: int64
    minimum: 1
Harness:
  name: harness
  in: path
  required: true
  schema:
    $ref: ./schemas/connections.yaml#/Harness
RecordingTabId:
  name: X-Recording-Tab-Id
  in: header
  required: true
  schema:
    type: integer
    format: int64
    minimum: 1
RecordingPageId:
  name: X-Recording-Page-Id
  in: header
  required: true
  schema:
    type: integer
    format: int64
    minimum: 1
RecordingTargetId:
  name: X-Recording-Target-Id
  in: header
  required: true
  schema:
    type: string
    minLength: 1
RecordingBatchId:
  name: X-Recording-Batch-Id
  in: header
  required: false
  schema:
    type: string
    minLength: 1
