/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as CChannelIdRouteImport } from './routes/c.$channelId'
import { Route as EEmployeeIdRouteImport } from './routes/e.$employeeId'
import { Route as EEmployeeIdIndexRouteImport } from './routes/e.$employeeId.index'
import { Route as EEmployeeIdNewRouteImport } from './routes/e.$employeeId.new'
import { Route as EEmployeeIdTThreadIdRouteImport } from './routes/e.$employeeId.t.$threadId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgRouteImport } from './routes/org'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsMcpRouteImport } from './routes/settings.mcp'
import { Route as SettingsSkillsRouteImport } from './routes/settings.skills'
import { Route as SettingsTelegramRouteImport } from './routes/settings.telegram'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTelegramRoute = SettingsTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSkillsRoute = SettingsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMcpRoute = SettingsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => SettingsRoute,
} as any)
const EEmployeeIdRoute = EEmployeeIdRouteImport.update({
  id: '/e/$employeeId',
  path: '/e/$employeeId',
  getParentRoute: () => rootRouteImport,
} as any)
const CChannelIdRoute = CChannelIdRouteImport.update({
  id: '/c/$channelId',
  path: '/c/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const EEmployeeIdIndexRoute = EEmployeeIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EEmployeeIdRoute,
} as any)
const EEmployeeIdNewRoute = EEmployeeIdNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EEmployeeIdRoute,
} as any)
const EEmployeeIdTThreadIdRoute = EEmployeeIdTThreadIdRouteImport.update({
  id: '/t/$threadId',
  path: '/t/$threadId',
  getParentRoute: () => EEmployeeIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/org': typeof OrgRoute
  '/settings': typeof SettingsRouteWithChildren
  '/c/$channelId': typeof CChannelIdRoute
  '/e/$employeeId': typeof EEmployeeIdRouteWithChildren
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/telegram': typeof SettingsTelegramRoute
  '/settings/': typeof SettingsIndexRoute
  '/e/$employeeId/new': typeof EEmployeeIdNewRoute
  '/e/$employeeId/': typeof EEmployeeIdIndexRoute
  '/e/$employeeId/t/$threadId': typeof EEmployeeIdTThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/org': typeof OrgRoute
  '/c/$channelId': typeof CChannelIdRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/telegram': typeof SettingsTelegramRoute
  '/settings': typeof SettingsIndexRoute
  '/e/$employeeId/new': typeof EEmployeeIdNewRoute
  '/e/$employeeId': typeof EEmployeeIdIndexRoute
  '/e/$employeeId/t/$threadId': typeof EEmployeeIdTThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/org': typeof OrgRoute
  '/settings': typeof SettingsRouteWithChildren
  '/c/$channelId': typeof CChannelIdRoute
  '/e/$employeeId': typeof EEmployeeIdRouteWithChildren
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/telegram': typeof SettingsTelegramRoute
  '/settings/': typeof SettingsIndexRoute
  '/e/$employeeId/new': typeof EEmployeeIdNewRoute
  '/e/$employeeId/': typeof EEmployeeIdIndexRoute
  '/e/$employeeId/t/$threadId': typeof EEmployeeIdTThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/org'
    | '/settings'
    | '/c/$channelId'
    | '/e/$employeeId'
    | '/settings/mcp'
    | '/settings/skills'
    | '/settings/telegram'
    | '/settings/'
    | '/e/$employeeId/new'
    | '/e/$employeeId/'
    | '/e/$employeeId/t/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/org'
    | '/c/$channelId'
    | '/settings/mcp'
    | '/settings/skills'
    | '/settings/telegram'
    | '/settings'
    | '/e/$employeeId/new'
    | '/e/$employeeId'
    | '/e/$employeeId/t/$threadId'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/org'
    | '/settings'
    | '/c/$channelId'
    | '/e/$employeeId'
    | '/settings/mcp'
    | '/settings/skills'
    | '/settings/telegram'
    | '/settings/'
    | '/e/$employeeId/new'
    | '/e/$employeeId/'
    | '/e/$employeeId/t/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  OrgRoute: typeof OrgRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  CChannelIdRoute: typeof CChannelIdRoute
  EEmployeeIdRoute: typeof EEmployeeIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/telegram': {
      id: '/settings/telegram'
      path: '/telegram'
      fullPath: '/settings/telegram'
      preLoaderRoute: typeof SettingsTelegramRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/skills': {
      id: '/settings/skills'
      path: '/skills'
      fullPath: '/settings/skills'
      preLoaderRoute: typeof SettingsSkillsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/mcp': {
      id: '/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof SettingsMcpRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/e/$employeeId': {
      id: '/e/$employeeId'
      path: '/e/$employeeId'
      fullPath: '/e/$employeeId'
      preLoaderRoute: typeof EEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$channelId': {
      id: '/c/$channelId'
      path: '/c/$channelId'
      fullPath: '/c/$channelId'
      preLoaderRoute: typeof CChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$employeeId/': {
      id: '/e/$employeeId/'
      path: '/'
      fullPath: '/e/$employeeId/'
      preLoaderRoute: typeof EEmployeeIdIndexRouteImport
      parentRoute: typeof EEmployeeIdRoute
    }
    '/e/$employeeId/new': {
      id: '/e/$employeeId/new'
      path: '/new'
      fullPath: '/e/$employeeId/new'
      preLoaderRoute: typeof EEmployeeIdNewRouteImport
      parentRoute: typeof EEmployeeIdRoute
    }
    '/e/$employeeId/t/$threadId': {
      id: '/e/$employeeId/t/$threadId'
      path: '/t/$threadId'
      fullPath: '/e/$employeeId/t/$threadId'
      preLoaderRoute: typeof EEmployeeIdTThreadIdRouteImport
      parentRoute: typeof EEmployeeIdRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsMcpRoute: typeof SettingsMcpRoute
  SettingsSkillsRoute: typeof SettingsSkillsRoute
  SettingsTelegramRoute: typeof SettingsTelegramRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsMcpRoute: SettingsMcpRoute,
  SettingsSkillsRoute: SettingsSkillsRoute,
  SettingsTelegramRoute: SettingsTelegramRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface EEmployeeIdRouteChildren {
  EEmployeeIdNewRoute: typeof EEmployeeIdNewRoute
  EEmployeeIdIndexRoute: typeof EEmployeeIdIndexRoute
  EEmployeeIdTThreadIdRoute: typeof EEmployeeIdTThreadIdRoute
}

const EEmployeeIdRouteChildren: EEmployeeIdRouteChildren = {
  EEmployeeIdNewRoute: EEmployeeIdNewRoute,
  EEmployeeIdIndexRoute: EEmployeeIdIndexRoute,
  EEmployeeIdTThreadIdRoute: EEmployeeIdTThreadIdRoute,
}

const EEmployeeIdRouteWithChildren = EEmployeeIdRoute._addFileChildren(
  EEmployeeIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  OrgRoute: OrgRoute,
  SettingsRoute: SettingsRouteWithChildren,
  CChannelIdRoute: CChannelIdRoute,
  EEmployeeIdRoute: EEmployeeIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
