import { readdir, readFile, readlink, stat } from 'node:fs/promises'
import { join, resolve as resolvePath, sep } from 'node:path'
import { resolveAgentSkillsDir } from 'agent-skills-manager'
import type { SupportedAgentKind } from '../../shared/agents/capabilities.constants.js'
import { AGENT_KINDS_WITH_SKILLS, toCatalogId } from './agent-mapping.js'
import { SKILLS_WORKSPACE_DIR } from './skills-workspace.js'

// Wire shape for skills found in agent skills dirs that BrowserClaw
// didn't install. They're surfaced in the picker so the agent can use
// them on `/`, but there's no DB row and no manifest mutation — the
// user owns the bundle.
export interface ExternalSkillRow {
  name: string
  description: string
  origin: 'external'
  agentKinds: SupportedAgentKind[]
}

/**
 * Scan each supported agent's skills directory for entries the user
 * installed outside BrowserClaw. An entry is "external" when its
 * resolved target is not inside our workspace dir — either a symlink
 * to somewhere else (another tool's store, a project-local path) or
 * a regular directory the user dropped in by hand.
 *
 * De-duplicates by skill name across agents. First agent that exposes
 * the name wins for description; the agentKinds array records every
 * agent that has it so the picker can hint which runtime can call it.
 */
export async function discoverExternalSkills(): Promise<ExternalSkillRow[]> {
  const byName = new Map<string, ExternalSkillRow>()
  for (const agentKind of AGENT_KINDS_WITH_SKILLS) {
    await scanAgentDir(agentKind, byName)
  }
  return Array.from(byName.values()).sort((a, b) =>
    a.name.localeCompare(b.name),
  )
}

async function scanAgentDir(
  agentKind: SupportedAgentKind,
  byName: Map<string, ExternalSkillRow>,
): Promise<void> {
  let agentDir: string
  try {
    agentDir = resolveAgentSkillsDir(toCatalogId(agentKind))
  } catch {
    return
  }
  let entries: string[]
  try {
    entries = await readdir(agentDir)
  } catch {
    return
  }
  for (const entry of entries) {
    if (entry.startsWith('.')) continue
    await scanEntry(agentDir, entry, agentKind, byName)
  }
}

async function scanEntry(
  agentDir: string,
  entry: string,
  agentKind: SupportedAgentKind,
  byName: Map<string, ExternalSkillRow>,
): Promise<void> {
  const entryPath = join(agentDir, entry)
  let frontmatter: { name: string; description: string } | null = null
  try {
    if (!(await isExternalSkillDir(entryPath, agentDir))) return
    frontmatter = await readFrontmatter(entryPath)
  } catch {
    return
  }
  if (!frontmatter) return

  const existing = byName.get(frontmatter.name)
  if (existing) {
    if (!existing.agentKinds.includes(agentKind)) {
      existing.agentKinds.push(agentKind)
    }
    return
  }
  byName.set(frontmatter.name, {
    name: frontmatter.name,
    description: frontmatter.description,
    origin: 'external',
    agentKinds: [agentKind],
  })
}

async function isExternalSkillDir(
  entryPath: string,
  agentDir: string,
): Promise<boolean> {
  const lst = await stat(entryPath)
  if (!lst.isDirectory()) return false
  let target = entryPath
  try {
    const link = await readlink(entryPath)
    target = resolvePath(agentDir, link)
  } catch {
    // not a symlink — real directory; target is the entry itself
  }
  return !target.startsWith(SKILLS_WORKSPACE_DIR + sep)
}

async function readFrontmatter(
  entryPath: string,
): Promise<{ name: string; description: string } | null> {
  const skillMd = join(entryPath, 'SKILL.md')
  const source = await readFile(skillMd, 'utf8')
  return parseSkillFrontmatter(source)
}

// Minimal SKILL.md frontmatter parser. The format is fixed and
// machine-generated by skill authors — no need for a YAML lib.
function parseSkillFrontmatter(
  source: string,
): { name: string; description: string } | null {
  const match = source.match(/^---\s*\r?\n([\s\S]+?)\r?\n---\s*(?:\r?\n|$)/)
  if (!match) return null
  const body = match[1]
  const name = extractField(body, 'name')
  const description = extractField(body, 'description')
  if (!name || !description) return null
  return { name, description }
}

function extractField(body: string, key: string): string | null {
  const re = new RegExp(`^${key}\\s*:\\s*(.+)$`, 'm')
  const m = body.match(re)
  if (!m) return null
  return m[1].trim().replace(/^["']|["']$/g, '')
}
