#!/usr/bin/env python3
"""Tests for bundled extension manifest handling."""

import json
import tempfile
import unittest
from pathlib import Path
from types import SimpleNamespace
from typing import cast

from bos_build.core.context import Context
from bos_build.core.products import get_product_descriptor
from bos_build.steps.extensions.bundled_extensions import (
    BundledExtensionsModule,
    ExtensionInfo,
)

CLAW_EXTENSION_ID = "pjimfkbpehlcllblajnpfamdfjhhlgkc"


class BundledExtensionsManifestTest(unittest.TestCase):
    def test_bundled_manifest_staging_file_is_coherent(self) -> None:
        # Structural check only: the file is regenerated by
        # `browseros release extensions`, so exact versions must not be pinned.
        repo_root = Path(__file__).resolve().parents[5]
        manifest_path = repo_root / "updates" / "extensions" / "bundled-manifest.xml"

        extensions = BundledExtensionsModule()._parse_manifest_xml(
            manifest_path.read_text()
        )

        by_id = {ext.id: ext for ext in extensions}
        required = get_product_descriptor("browseros").required_extension_ids
        for extension_id, name in required:
            self.assertIn(extension_id, by_id, name)

        for ext in extensions:
            self.assertRegex(
                ext.codebase,
                r"^https://cdn\.browseros\.com/extensions/[a-z]+-[0-9.]+\.crx$",
            )
            self.assertTrue(ext.version)
            self.assertIn(f"-{ext.version}.crx", ext.codebase)

    def test_required_ids_cover_agent_bug_reporter_and_claw(self) -> None:
        # Both products bundle all three until the chromium-side fix lands
        # (see the required_extension_ids TODO in common/products.py).
        expected = {
            "adlpneommgkgeanpaekgoaolcpncohkf": "BrowserOS bug reporter",
            "bflpfmnmnokmjhmgnolecpppdbdophmk": "BrowserOS agent",
            CLAW_EXTENSION_ID: "BrowserClaw app",
        }
        self.assertEqual(
            dict(get_product_descriptor("browseros").required_extension_ids),
            expected,
        )
        self.assertEqual(
            dict(get_product_descriptor("browserclaw").required_extension_ids),
            expected,
        )

    def test_generated_json_maps_claw_id_to_crx(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output_dir = Path(tmp)
            BundledExtensionsModule()._generate_json(
                [
                    ExtensionInfo(
                        id=CLAW_EXTENSION_ID,
                        version="0.0.1",
                        codebase=(
                            "https://cdn.browseros.com/extensions/"
                            "browserclaw-0.0.1.crx"
                        ),
                    )
                ],
                output_dir,
            )

            data = json.loads((output_dir / "bundled_extensions.json").read_text())

        self.assertEqual(
            data[CLAW_EXTENSION_ID],
            {
                "external_crx": f"{CLAW_EXTENSION_ID}.crx",
                "external_version": "0.0.1",
            },
        )

    def test_missing_claw_app_fails_validation(self) -> None:
        extensions = [
            ExtensionInfo(
                id="adlpneommgkgeanpaekgoaolcpncohkf",
                version="52.0.0.0",
                codebase="https://cdn.browseros.com/extensions/bugreporter.crx",
            ),
            ExtensionInfo(
                id="bflpfmnmnokmjhmgnolecpppdbdophmk",
                version="0.0.115.0",
                codebase="https://cdn.browseros.com/extensions/agent.crx",
            ),
        ]

        with self.assertRaisesRegex(
            RuntimeError,
            f"BrowserClaw app \\({CLAW_EXTENSION_ID}\\)",
        ):
            BundledExtensionsModule()._validate_required_extensions(
                extensions, self._ctx("browserclaw")
            )

    def test_browserclaw_selects_all_required_extensions(self) -> None:
        extensions = [
            ExtensionInfo(
                id="adlpneommgkgeanpaekgoaolcpncohkf",
                version="52.0.0.0",
                codebase="https://cdn.browseros.com/extensions/bugreporter.crx",
            ),
            ExtensionInfo(
                id="bflpfmnmnokmjhmgnolecpppdbdophmk",
                version="0.0.115.0",
                codebase="https://cdn.browseros.com/extensions/agent.crx",
            ),
            ExtensionInfo(
                id=CLAW_EXTENSION_ID,
                version="0.0.1",
                codebase="https://cdn.browseros.com/extensions/browserclaw.crx",
            ),
        ]

        selected = BundledExtensionsModule()._select_product_extensions(
            extensions, self._ctx("browserclaw")
        )

        # All three ship for browserclaw too while the packaging TODO stands.
        self.assertEqual(
            [ext.id for ext in selected],
            [
                "adlpneommgkgeanpaekgoaolcpncohkf",
                "bflpfmnmnokmjhmgnolecpppdbdophmk",
                CLAW_EXTENSION_ID,
            ],
        )

    def _ctx(self, product: str):
        return cast(
            Context, SimpleNamespace(product=get_product_descriptor(product))
        )


if __name__ == "__main__":
    unittest.main()
